version: '3.4'

services:
  leaderboardwebapi:
    container_name: webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;http://+:8080
      - ASPNETCORE_MANAGEMENTPORT=8080
      - ConnectionStrings__LeaderboardContext=Server=sql.retrogaming.internal;Database=Leaderboard;User Id=sa;Password=Pass@word;Trusted_Connection=False;TrustServerCertificate=true
      #- KeyVaultUri=https://conferencedemoskeyvault.vault.azure.net/
    ports:
      - 4972:80
      - 44369:443
    depends_on:
      - sql.data
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - frontend
      - backend

  gamingwebapp:
    container_name: webapp
    environment:
      - OTEL_DOTNET_AUTO_CONTAINER_RESOURCE_DETECTOR_ENABLED=true
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - LeaderboardApiOptions__BaseUrl=http://leaderboardwebapi
    ports:
      - 5618:80
      - 44325:443
    depends_on:
      - leaderboardwebapi
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - frontend

  sql.data:
    container_name: sql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=Pass@word
      - MSSQL_PID=Developer
      - ACCEPT_EULA=Y
    ports:
      - "1433"
    networks:
      backend:
        aliases: 
          - sql.retrogaming.internal

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment: 
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
    networks:
      - backend

  # healthcheckui:
  #   image: xabarilcoding/healthchecksui:latest
  #   environment:
  #     - HealthChecksUI:HealthChecks:0:Name=Readiness checks
  #     - HealthChecksUI:HealthChecks:0:Uri=http://leaderboardwebapi:8080/health/ready
  #     - HealthChecksUI:HealthChecks:1:Name=Liveliness checks
  #     - HealthChecksUI:HealthChecks:1:Uri=http://leaderboardwebapi:8080/health/lively
  #   ports:
  #     - 5000:80
  #   networks:
  #     - backend

  zipkin:
    image: ghcr.io/openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - frontend
      - backend

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true 
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - 16686:16686 
      - 4317:4317 
      - 4318:4318 
    networks:
      - frontend
      - backend

  dotnet-monitor:
    image: mcr.microsoft.com/dotnet/monitor:7
    ports: 
      - 52323:52323
    environment:
      - DOTNETMONITOR_Authentication:MonitorApiKey:Subject=a65223c0-4066-4594-ae46-f3a1fad83a37
      - DOTNETMONITOR_Authentication:MonitorApiKey:PublicKey=eyJBZGRpdGlvbmFsRGF0YSI6e30sIkNydiI6IlAtMzg0IiwiS2V5T3BzIjpbXSwiS3R5IjoiRUMiLCJYIjoiZDk0SFNXQXdrbmxPZTNBWWJhRTVfVmxJTFd5QVNhbDhvQkV2bHM2YTZucVVvcUVCQ04zZVhUNmtDb216S0syRyIsIlg1YyI6W10sIlkiOiJmb3RySFh6Sml2ZGN2RUVoY24zVlZtVUt4Q1ZrVk4wSnVxaUVmRFQxblhEN3VhTTZMcmRDUEVXRzB4dDBHYW1FIiwiS2V5U2l6ZSI6Mzg0LCJIYXNQcml2YXRlS2V5IjpmYWxzZSwiQ3J5cHRvUHJvdmlkZXJGYWN0b3J5Ijp7IkNyeXB0b1Byb3ZpZGVyQ2FjaGUiOnt9LCJDYWNoZVNpZ25hdHVyZVByb3ZpZGVycyI6dHJ1ZSwiU2lnbmF0dXJlUHJvdmlkZXJPYmplY3RQb29sQ2FjaGVTaXplIjoyNH19
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge