version: '3.4'

services:
  leaderboardwebapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80;http://+:8080
      - ASPNETCORE_MANAGEMENTPORT=8080
      - KESTREL__CERTIFICATES__DEFAULT__PATH=/https/aspnetapp.pfx
      - ConnectionStrings__LeaderboardContext=Server=sql.retrogasming.internal;Database=Leaderboard;User Id=sa;Password=Pass@word;Trusted_Connection=False;TrustServerCertificate=true
      #- KeyVaultUri=https://conferencedemoskeyvault.vault.azure.net/
    ports:
      - "4972:80"
      - "44369:443"
    depends_on:
      - sql.data
    volumes:
       - ${HOME}/.aspnet/dev-certs/https:/.aspnet/dev-certs/
#      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - frontend
      - backend

  gamingwebapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - LeaderboardApiOptions__BaseUrl=http://leaderboardwebapi
    ports:
      - "5618:80"
      - "44325:443"
    depends_on:
      - leaderboardwebapi
    volumes:
      -  ${HOME}/.aspnet/https:/https/
#      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - frontend

  sql.data:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=Pass@word
      - MSSQL_PID=Developer
      - ACCEPT_EULA=Y
    ports:
      - "1433"
    networks:
      backend:
        aliases: 
          - sql.retrogaming.internal

  seq:
    image: datalust/seq:latest
    environment: 
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
    networks:
      - backend

  # healthcheckui:
  #   image: xabarilcoding/healthchecksui:latest
  #   environment:
  #     - HealthChecksUI:HealthChecks:0:Name=Readiness checks
  #     - HealthChecksUI:HealthChecks:0:Uri=http://leaderboardwebapi:8080/health/ready
  #     - HealthChecksUI:HealthChecks:1:Name=Liveliness checks
  #     - HealthChecksUI:HealthChecks:1:Uri=http://leaderboardwebapi:8080/health/lively
  #   ports:
  #     - 5000:80
  #   networks:
  #     - backend

  dotnet-monitor:
    image: mcr.microsoft.com/dotnet/monitor:7
    ports: 
      - 52323:52323
    environment:
      - DOTNETMONITOR_Authentication:MonitorApiKey:Subject=a65223c0-4066-4594-ae46-f3a1fad83a37
      - DOTNETMONITOR_Authentication:MonitorApiKey:PublicKey=eyJBZGRpdGlvbmFsRGF0YSI6e30sIkNydiI6IlAtMzg0IiwiS2V5T3BzIjpbXSwiS3R5IjoiRUMiLCJYIjoiZDk0SFNXQXdrbmxPZTNBWWJhRTVfVmxJTFd5QVNhbDhvQkV2bHM2YTZucVVvcUVCQ04zZVhUNmtDb216S0syRyIsIlg1YyI6W10sIlkiOiJmb3RySFh6Sml2ZGN2RUVoY24zVlZtVUt4Q1ZrVk4wSnVxaUVmRFQxblhEN3VhTTZMcmRDUEVXRzB4dDBHYW1FIiwiS2V5U2l6ZSI6Mzg0LCJIYXNQcml2YXRlS2V5IjpmYWxzZSwiQ3J5cHRvUHJvdmlkZXJGYWN0b3J5Ijp7IkNyeXB0b1Byb3ZpZGVyQ2FjaGUiOnt9LCJDYWNoZVNpZ25hdHVyZVByb3ZpZGVycyI6dHJ1ZSwiU2lnbmF0dXJlUHJvdmlkZXJPYmplY3RQb29sQ2FjaGVTaXplIjoyNH19
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge