apiVersion: v1
kind: Service
metadata:
  name: svc-gamingwebapp
  labels:
    version: dev
    product: RetroGaming
spec:
  type: LoadBalancer
  selector:
    app: gamingwebapp
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
---
apiVersion: v1
kind: Service
metadata:
  name: svc-leaderboardwebapi
  labels:
    version: dev
    product: RetroGaming
spec:
  selector:
    app: leaderboardwebapi
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-gamingwebapp
spec:
  selector:
    matchLabels:
      app : gamingwebapp
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gamingwebapp
    spec:
      containers:
      - name: gamingwebapp
        terminationMessagePath: "/tmp/gamingwebapp-log"
        image: local/gamingwebapp:latest
        imagePullPolicy: Never
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: http://0.0.0.0:80
        - name: LeaderboardApiOptions__BaseUrl
          value: http://svc-leaderboardwebapi
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            cpu: "0.10"
      imagePullSecrets:
        - name: pullkey
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-leaderboardwebapi
spec:
  selector:
    matchLabels:
      app : leaderboardwebapi
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: leaderboardwebapi
    spec:
      volumes:
      - name: secretsettings
        secret:
          secretName: secret-appsettings
      containers:
      - name: leaderboardwebapi
        terminationMessagePath: "/tmp/leaderboardwebapi-log"
        image: local/leaderboardwebapi:health
        imagePullPolicy: Never
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 20
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /health/lively
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 20
          failureThreshold: 3
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: Logging__LogLevel__Default
          value: Debug
        - name: Logging__LogLevel__Microsoft
          value: Debug
        - name: KeyVaultName
          value: https://yourkeyvault.vault.azure.net/
        - name: ASPNETCORE_MANAGEMENTPORT
          value: "8080"
        - name: ASPNETCORE_URLS
          value: http://+:80;http://+:8080
        ports:
        - containerPort: 80
        - containerPort: 8080
        - containerPort: 443
        resources:
          limits:
            cpu: "0.10"
        volumeMounts:
        - name: secretsettings
          mountPath: /app/secrets
          readOnly: true
      imagePullSecrets:
        - name: pullkey
