FROM mcr.microsoft.com/devcontainers/dotnet:1-8.0

COPY --from=mcr.microsoft.com/dotnet/sdk:9.0 /usr/share/dotnet/ /usr/share/dotnet/
COPY --from=mcr.microsoft.com/dotnet/sdk:10.0 /usr/share/dotnet/ /usr/share/dotnet/
