receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  # logging:
  #   verbosity: detailed
    
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
      
  otlphttp/seq:
    endpoint: http://seq:5341/ingest/otlp/
  
  azuremonitor:
    connection_string: InstrumentationKey=
    spaneventsenabled: true
    maxbatchsize: 100
    maxbatchinterval: 10s
  
  prometheus:
    endpoint: 0.0.0.0:8889
  
  otlp/aspire-dashboard:
    endpoint: aspire-dashboard:18889
    tls:
      insecure: true

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"
    path: "/health/status"
    check_collector_pipeline:
      enabled: true
      interval: "5m"
      exporter_failure_threshold: 5

processors:
  batch:

service:
  telemetry:
    logs:
      level: "debug"
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/jaeger, azuremonitor, otlp/aspire-dashboard]
      processors: [batch]
    metrics:
      receivers: [otlp]
      exporters: [prometheus, azuremonitor, otlp/aspire-dashboard]
      processors: [batch]
    logs:
      receivers: [otlp]
      exporters: [otlphttp/seq, azuremonitor, otlp/aspire-dashboard]
      processors: [batch]