receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    verbosity: detailed
    
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
      
  otlphttp/seq:
    endpoint: http://seq:5341/ingest/otlp/
    
  azuremonitor:
    connection_string: "insert key"
    spaneventsenabled: true
  
  prometheus:
    endpoint: 0.0.0.0:8889
  
  otlp/aspire-dashboard:
    endpoint: aspire-dashboard:18889
    tls:
      insecure: true
  
extensions:
  health_check:
    endpoint: "0.0.0.0:13133"
    path: "/health/status"
    check_collector_pipeline:
      enabled: true
      interval: "5m"
      exporter_failure_threshold: 5

processors:
  batch:

service:
  telemetry:
    logs:
      level: "debug"
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp/jaeger, azuremonitor, otlp/aspire-dashboard]
      processors: [batch]
    metrics:
      receivers: [otlp]
      exporters: [logging, prometheus, azuremonitor, otlp/aspire-dashboard]
      processors: [batch]
    logs:
      receivers: [otlp]
      exporters: [logging, otlphttp/seq, azuremonitor, otlp/aspire-dashboard]
      processors: [batch]